apiVersion: v1
kind: ConfigMap
metadata:
  name: stocksense-config
  namespace: stocksense
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  DATABASE_URL: "postgresql+asyncpg://postgres:1234@postgres-service:5432/stocksense"
  POSTGRES_DB: "stocksense"
  POSTGRES_USER: "postgres"
