apiVersion: v1
kind: Secret
metadata:
  name: stocksense-secret
  namespace: stocksense
type: Opaque
stringData:
  POSTGRES_PASSWORD: "1234"
  # .env 파일의 다른 시크릿 값들을 여기에 추가하세요
  # 예: API_KEY: "your-api-key"
